name: Vercel development Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout private data 🔨
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build Gatsby site 🔨
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: public
          path: public

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Build Project Artifacts
      #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        # run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd public_html
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd public_html
